# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a command to create the addon file
    - name: Create addon file
      run: .vendor/gmad.exe create -folder . -out abrm-toybox.gma
      
    # Runs a command to update the workshop addon
    #- name: Update workshop addon
    #  run: .vendor/gmpublish.exe update -id 2208941058 -icon addon-icon.jpg -addon abrm-toybox.gma -changes "${{ github.sha }}"
    
    # Create a release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}

    # Upload a release asset
    - name: Upload release asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./abrm-toybox.gma
          asset_name: abrm-toybox.gma
          asset_content_type: application/octet-stream
